include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas
    - prefer_single_quotes
    - prefer_relative_imports
    - directives_ordering
    - avoid_print: false
